apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-test"
  annotations:
    github.com/project-slug: jwhong3004/backstage-ec2
    backstage.io/techdocs-ref: dir:.
  title: 'Create EC2 instance' # you can give any title
  description: An example of a Instance Creation. # Change Description accordingly
spec:
  type: service
  owner: guests
  lifecycle: experimental
