apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: '{{ (range(1000) | random | string) }}'
  annotations:
    github.com/project-slug: jwhong3004/backstage-ec2
    backstage.io/techdocs-ref: dir:.
  title: '${{ values.name | dump }} / EC2 instance / ${{ values.repo | dump }}' # you can give any title
  description: An example of a Instance Creation. # Change Description accordingly
spec:
  type: service
  owner: guests
  lifecycle: experimental
