apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    github.com/project-slug: jwhong3004/backstage-ec2
    backstage.io/techdocs-ref: dir:.
  title: '${{ values.name | dump }} / EC2 instance' # you can give any title
  description: 'An example of a Instance Creation. repo: ${{ values.repo | dump }}'
spec:
  type: service
  owner: guests
  lifecycle: experimental
