apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    github.com/project-slug: jwhong3004/backstage-application
    backstage.io/techdocs-ref: url:https://github.com/jwhong3004/${{ values.repo }}/tree/master
    github.com/workflows: application.yml
    backstage.io/kubernetes-label-selector: 'app=${{ values.name }}'
  title: '${{ values.name | dump }} / EC2 Application'
  description: 'An example of a Application Creation.'
spec:
  type: service
  owner: guests
  lifecycle: experimental
